/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aayusharijal
 */
public class MeroSchool extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MeroSchool.class.getName());

    /**
     * Creates new form MeroSchool
     */
    public MeroSchool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        pnlMainScreenTitleBar = new javax.swing.JPanel();
        ibiMianScreenLogo = new javax.swing.JLabel();
        ibiMainScreenTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTabStudentList = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlTabAdminControl = new javax.swing.JPanel();
        pnlAboutUs = new javax.swing.JPanel();
        pnlTabHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MeroSchool");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));

        pnlMainScreen.setBackground(new java.awt.Color(0, 0, 0));

        pnlMainScreenTitleBar.setBackground(new java.awt.Color(234, 192, 32));

        ibiMianScreenLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ibiMianScreenLogo.setText("jLabel1");

        ibiMainScreenTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        ibiMainScreenTitle.setText("Empowering Student,Simplifying Management");

        javax.swing.GroupLayout pnlMainScreenTitleBarLayout = new javax.swing.GroupLayout(pnlMainScreenTitleBar);
        pnlMainScreenTitleBar.setLayout(pnlMainScreenTitleBarLayout);
        pnlMainScreenTitleBarLayout.setHorizontalGroup(
            pnlMainScreenTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenTitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ibiMianScreenLogo)
                .addGap(49, 49, 49)
                .addComponent(ibiMainScreenTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainScreenTitleBarLayout.setVerticalGroup(
            pnlMainScreenTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenTitleBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlMainScreenTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibiMianScreenLogo)
                    .addComponent(ibiMainScreenTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(234, 192, 32));

        pnlTabStudentList.setBackground(new java.awt.Color(234, 192, 32));

        jTable1.setBackground(new java.awt.Color(234, 192, 32));
        jTable1.setForeground(new java.awt.Color(234, 192, 32));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "lmuId", "Full Name", "Program", "Contact", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlTabStudentList.addTab("Student Information", jScrollPane1);

        jTabbedPane1.addTab("Studnet List", pnlTabStudentList);

        javax.swing.GroupLayout pnlTabAdminControlLayout = new javax.swing.GroupLayout(pnlTabAdminControl);
        pnlTabAdminControl.setLayout(pnlTabAdminControlLayout);
        pnlTabAdminControlLayout.setHorizontalGroup(
            pnlTabAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        pnlTabAdminControlLayout.setVerticalGroup(
            pnlTabAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Admin Control", pnlTabAdminControl);

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Us", pnlAboutUs);

        pnlTabHome.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlTabHomeLayout = new javax.swing.GroupLayout(pnlTabHome);
        pnlTabHome.setLayout(pnlTabHomeLayout);
        pnlTabHomeLayout.setHorizontalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        pnlTabHomeLayout.setVerticalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Home", pnlTabHome);

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(pnlMainScreenTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainScreenTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MeroSchool().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ibiMainScreenTitle;
    private javax.swing.JLabel ibiMianScreenLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlMainScreenTitleBar;
    private javax.swing.JPanel pnlTabAdminControl;
    private javax.swing.JPanel pnlTabHome;
    private javax.swing.JTabbedPane pnlTabStudentList;
    // End of variables declaration//GEN-END:variables
}
